#!/bin/sh
set -ex
(
  set -ex
  cd yi
  cabal install --only-dependencies
  cabal install --force-reinstalls
)
(
  set -ex
  cd yi-contrib
  cabal install --only-dependencies
  cabal install --force-reinstalls
)

